name: salt_ware_tax
description: "Document Scanner Tax Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  cunning_document_scanner: ^1.2.3
  url_launcher: ^6.3.1
  animated_bottom_navigation_bar: ^1.3.3
  lottie: ^3.1.3
  provider: ^6.1.2
  toastification: ^2.3.0
  shared_preferences: ^2.4.0
  animated_text_kit: ^4.2.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/main_app_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/main_app_logo.png"


flutter:
  uses-material-design: true

  fonts:
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/poppins_semi_bold.ttf

    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/poppins_regular.ttf

  assets:
    - assets/icons/app_logo.png
    - assets/loader/loading.json
    - assets/loader/profile.json
    - assets/loader/no_data.json
    - assets/icons/folder.png
    - assets/icons/bottom_nav_home.png
    - assets/icons/bottom_nav_scan.png
    - assets/icons/bottom_nav_profile.png
    - assets/icons/home_alpha.png
    - assets/icons/home_grid.png
    - assets/icons/home_list.png
    - assets/icons/home_search.png
    - assets/images/back_arrow.png
    - assets/images/copy_link.png
    - assets/images/open_link.png
    - assets/images/log_out.png
    - assets/images/splash_screen_logo.png


flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#FFFFFF"
  image: "assets/images/splash_screen_logo.png"

  android_12:
    color: "#FFFFFF"
    image: "assets/images/splash_screen_logo.png"